  
AWSTemplateFormatVersion: '2010-09-09'
Description:
  SecurityGroup create
Parameters:
  ProjectId:
    Description: Project name id.
    Type: String
    MinLength: "3"
    MaxLength: "10"
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must specify Project id.

Resources:
  # WebServer SG
  WebServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "PublicSgForWeb"
      GroupDescription: "SecurityGroup for WebServer(public)"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: name
          Value: !Join [ "-", [ "Ref":"ProjectId" ,"SecurityGroupForWebServer" ] ]
      VpcId: !ImportValue "network-VPCID"

  # RDS SG
  RdsSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "PrivateSgForRDS"
      GroupDescription: "SecurityGroup for RDS(private)"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.1.0/24
      Tags:
        - Key: name
          Value: !Join [ "-", ["Ref":"ProjectId", "SecurityGroupForRDS"] ]
  
Outputs:
  StackWebServerSG:
    Value: !Ref WebServerSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-WebServerSG"
  
  StackRdsSG:
    Value: !Ref RdsSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-RdsSG"